### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by staminna** [MNBoy/nuxt-invoice-app#2]
Hi MNBoy

Any plans to move into Next 3.x?

[
<img width="889" alt="Captura de ecrã 2022-12-19, às 21 02 43" src="https://user-images.githubusercontent.com/515180/208523551-0479e13c-2bcf-4555-b020-c1e1eb6f006f.png">
](url)

node -v

16.16.0

**Comment by MNBoy** [comment]
Hi. Sorry but no. Because it's a training project and I don't use vue or nuxt anymore
